# Generated by Django 3.0.7 on 2020-06-11 08:34

import challenge.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Lig', 'L'), ('frindy', 'F')], max_length=9)),
                ('score', models.IntegerField(default=0)),
                ('pos', models.CharField(blank=True, max_length=10)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to=challenge.models.where_to_upload)),
                ('language', models.CharField(choices=[('c++', 'C++'), ('java', 'Java'), ('python', 'Python'), ('go', 'Go')], default='python', max_length=10)),
                ('status', models.CharField(choices=[('compiling', 0), ('compiled', 1), ('Eroro', -1)], max_length=9)),
                ('date', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='photo/team/%Y/%m/%d')),
                ('active', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('message_box', models.ManyToManyField(to='challenge.PostMessage')),
                ('score', models.ManyToManyField(blank=True, related_name='members', to='challenge.Score')),
                ('submission', models.ManyToManyField(blank=True, to='challenge.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.IntegerField(choices=[(1, 1), (3, 3), (2, 2)])),
                ('discribtion', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team1_result', models.IntegerField(default=0)),
                ('team2_result', models.IntegerField(default=0)),
                ('game_type', models.CharField(choices=[('f_random', 'R'), ('Lig', 'L'), ('tornoment', 'T'), ('f_normal', 'N')], default='friendly', max_length=50)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='challenge.Team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='challenge.Team')),
            ],
        ),
    ]
